[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "agentmodel"
version = "0.0.2"
description = "Agent's data model"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
]
