name: Publish to PyPI

on:
  push:
    tags:
      - 'v*.*.*'

permissions: write-all

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: publish-pypi
              uses: bitovi/github-actions-publish-github-pypi@main
              with:
                github-token: ${{ secrets.PYPI_GITHUB_TOKEN }}
                pypi-github-org: bitovi
                pypi-github-repo: PyPI
                pypi-github-workflow-ref: initial-working