name: Publish to PyPI

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

permissions: write-all

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: publish-pypi
      uses: bitovi/github-actions-publish-github-pypi@main
      with:
        github-token: ${{ secrets.GH_TOKEN_PYPI_DEP }}
        pypi-github-org: bitovi
        pypi-github-repo: PyPI
        pypi-github-workflow-ref: initial-working